FROM --platform=linux/amd64 jenkins/jenkins:latest
USER root

RUN apt-get update && \
    apt-get install -y python3-pip python3-venv wget curl unzip gnupg

RUN curl -fsSL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update

RUN apt-get install -y google-chrome-stable

RUN wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
  && apt install -y /tmp/chrome.deb \
  && rm /tmp/chrome.deb

RUN wget -qO- https://github.com/allure-framework/allure2/releases/download/2.17.3/allure-2.17.3.tgz | tar -xz -C /opt/ && \
    ln -s /opt/allure-2.17.3/bin/allure /usr/bin/allure

# Install xvfb for headless working
RUN apt-get install -y xvfb

# Очистка
#RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# Возвращаемся к пользователю Jenkins
USER jenkins

#RUN apt-get install -y wget unzip chromium-browser
#RUN apt update
#RUN apt-get install -y wget unzip
#RUN CHROMEDRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
#RUN wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -O chromedriver.zip
#
#RUN unzip chromedriver.zip -d /usr/local/bin/
#RUN rm chromedriver.zip
#RUN apt-get update
#
#RUN apt-get install -y xvfb
#RUN apt install python3.11-venv
#
#RUN apt-get install google-chrome-stable
#RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

