pipeline {
    agent any
    triggers {
        cron('H H * * 1')
    }
    stages {
        stage('Clean Workspace') {
            steps {
                deleteDir() // Удаление предыдущих файлов
            }
        }
        stage('Setup Environment') {
            steps {
                script {
                    echo 'Setting up environment...'
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Run API Tests') {
            steps {
                script {
                    echo 'Running API tests...'
                    sh '''
                        . venv/bin/activate
                        export PYTHONPATH=$PYTHONPATH:/var/jenkins_home/workspace/API_pipeline
                        pytest --alluredir=allure-results -m API
                    '''
                }
            }
        }
    }
    post {
        always {
            allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
        }
    }
}
